env:
  browser: true
  commonjs: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  no-var: error
  semi:
    - error
    - always
  comma-dangle:
    - error
    - never
